name: CI/CD - Docker Build & Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t online-clone-amazon:latest .

      - name: Run smoke test
        run: |
          docker run -d -p 8080:80 online-clone-amazon:latest
          sleep 5
          curl -f http://localhost:8080 || (docker logs $(docker ps -lq) && exit 1)

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag online-clone-amazon:latest ${{ secrets.DOCKER_HUB_USERNAME }}/online-clone-amazon:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/online-clone-amazon:latest
